# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T10:15:44+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class Tax(BaseModel):
    Country: Optional[str] = Field(None, examples=['<string>'])
    Type: Optional[str] = Field(None, examples=['<string>'])
    data_name: Optional[str] = Field(None, examples=['<string>'])
    data_value: Optional[str] = Field(None, examples=['<string>'])


class V1TaxCountrycodeGetResponse(BaseModel):
    country_name: Optional[str] = Field(None, examples=['<string>'])
    taxes: Optional[List[Tax]] = Field(
        None,
        examples=[
            [
                {
                    'Country': '<string>',
                    'Type': '<string>',
                    'data_name': '<string>',
                    'data_value': '<string>',
                },
                {
                    'Country': '<string>',
                    'Type': '<string>',
                    'data_name': '<string>',
                    'data_value': '<string>',
                },
            ]
        ],
    )


class V1TaxCountrycodeGetResponse1(BaseModel):
    code: Optional[str] = Field(None, examples=['<integer>'])
    fields: Optional[str] = Field(None, examples=['<string>'])
    message: Optional[str] = Field(None, examples=['<string>'])


class V1TaxIpGetResponseItem(BaseModel):
    country_name: Optional[str] = Field(None, examples=['<string>'])
    taxes: Optional[List[Tax]] = Field(
        None,
        examples=[
            [
                {
                    'Country': '<string>',
                    'Type': '<string>',
                    'data_name': '<string>',
                    'data_value': '<string>',
                },
                {
                    'Country': '<string>',
                    'Type': '<string>',
                    'data_name': '<string>',
                    'data_value': '<string>',
                },
            ]
        ],
    )


class V1TaxIpGetResponse(RootModel[List[V1TaxIpGetResponseItem]]):
    root: List[V1TaxIpGetResponseItem] = Field(
        ...,
        examples=[
            [
                {
                    'country_name': '<string>',
                    'taxes': [
                        {
                            'Country': '<string>',
                            'Type': '<string>',
                            'data_name': '<string>',
                            'data_value': '<string>',
                        },
                        {
                            'Country': '<string>',
                            'Type': '<string>',
                            'data_name': '<string>',
                            'data_value': '<string>',
                        },
                    ],
                },
                {
                    'country_name': '<string>',
                    'taxes': [
                        {
                            'Country': '<string>',
                            'Type': '<string>',
                            'data_name': '<string>',
                            'data_value': '<string>',
                        },
                        {
                            'Country': '<string>',
                            'Type': '<string>',
                            'data_name': '<string>',
                            'data_value': '<string>',
                        },
                    ],
                },
            ]
        ],
    )


class V1TaxIpGetResponse1(BaseModel):
    code: Optional[str] = Field(None, examples=['<integer>'])
    fields: Optional[str] = Field(None, examples=['<string>'])
    message: Optional[str] = Field(None, examples=['<string>'])


class Rate(BaseModel):
    data_name: Optional[str] = Field(None, examples=['<string>'])
    data_value: Optional[str] = Field(None, examples=['<string>'])
    product_code: Optional[str] = Field(None, examples=['<string>'])
    type: Optional[str] = Field(None, examples=['<string>'])


class V3TaxRatesGetResponseItem(BaseModel):
    id: Optional[str] = Field(None, examples=['<integer>'])
    name: Optional[str] = Field(None, examples=['<string>'])
    rates: Optional[List[Rate]] = Field(
        None,
        examples=[
            [
                {
                    'data_name': '<string>',
                    'data_value': '<string>',
                    'product_code': '<string>',
                    'type': '<string>',
                },
                {
                    'data_name': '<string>',
                    'data_value': '<string>',
                    'product_code': '<string>',
                    'type': '<string>',
                },
            ]
        ],
    )
    state: Optional[str] = Field(None, examples=['<string>'])
    zip: Optional[str] = Field(None, examples=['<string>'])


class V3TaxRatesGetResponse(RootModel[List[V3TaxRatesGetResponseItem]]):
    root: List[V3TaxRatesGetResponseItem] = Field(
        ...,
        examples=[
            [
                {
                    'id': '<integer>',
                    'name': '<string>',
                    'rates': [
                        {
                            'data_name': '<string>',
                            'data_value': '<string>',
                            'product_code': '<string>',
                            'type': '<string>',
                        },
                        {
                            'data_name': '<string>',
                            'data_value': '<string>',
                            'product_code': '<string>',
                            'type': '<string>',
                        },
                    ],
                    'state': '<string>',
                    'zip': '<string>',
                },
                {
                    'id': '<integer>',
                    'name': '<string>',
                    'rates': [
                        {
                            'data_name': '<string>',
                            'data_value': '<string>',
                            'product_code': '<string>',
                            'type': '<string>',
                        },
                        {
                            'data_name': '<string>',
                            'data_value': '<string>',
                            'product_code': '<string>',
                            'type': '<string>',
                        },
                    ],
                    'state': '<string>',
                    'zip': '<string>',
                },
            ]
        ],
    )


class V3TaxRatesGetResponse1(BaseModel):
    code: Optional[str] = Field(None, examples=['<integer>'])
    fields: Optional[str] = Field(None, examples=['<string>'])
    message: Optional[str] = Field(None, examples=['<string>'])
